//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class art_tarifs_globales
    {
        public long Row { get; set; }
        public string AR_Ref { get; set; }
        public string AR_Design { get; set; }
        public Nullable<decimal> prix_veNte { get; set; }
        public Nullable<int> cat { get; set; }
        public string TC_RefCF { get; set; }
        public Nullable<decimal> EC_Quantite { get; set; }
        public string EC_Enumere { get; set; }
    }
}
