//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEMO_NEGOCEEntities : DbContext
    {
        public DEMO_NEGOCEEntities()
            : base("name=DEMO_NEGOCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<F_DOCCURRENTPIECE> F_DOCCURRENTPIECE { get; set; }
        public DbSet<F_ARTSTOCK> F_ARTSTOCK { get; set; }
        public DbSet<F_ARTCOMPTA> F_ARTCOMPTA { get; set; }
        public DbSet<F_FAMCOMPTA> F_FAMCOMPTA { get; set; }
        public DbSet<F_TAXE> F_TAXE { get; set; }
        public DbSet<F_LIVRAISON> F_LIVRAISON { get; set; }
        public DbSet<F_ARTCLIENT> F_ARTCLIENT { get; set; }
        public DbSet<F_COMPTET> F_COMPTET { get; set; }
        public DbSet<F_CREGLEMENT> F_CREGLEMENT { get; set; }
        public DbSet<P_REGLEMENT> P_REGLEMENT { get; set; }
        public DbSet<F_COMPTETV> F_COMPTETV { get; set; }
        public DbSet<art_tarifs_globales> art_tarifs_globales { get; set; }
        public DbSet<F_DOCLIGNE> F_DOCLIGNE { get; set; }
        public DbSet<F_DOCREGL> F_DOCREGL { get; set; }
        public DbSet<F_COLLABORATEUR> F_COLLABORATEUR { get; set; }
        public DbSet<SOLDE_CLT> SOLDE_CLT { get; set; }
        public DbSet<STAT_CAT> STAT_CAT { get; set; }
        public DbSet<STAT_CLT> STAT_CLT { get; set; }
        public DbSet<STAT_ART> STAT_ART { get; set; }
        public DbSet<F_ARTICLESALLPRICE> F_ARTICLESALLPRICE { get; set; }
        public DbSet<F_ARTICLE> F_ARTICLE { get; set; }
        public DbSet<F_DOCENTETE> F_DOCENTETE { get; set; }
        public DbSet<AssClientArt> AssClientArt { get; set; }
    }
}
