//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTCOMPTA
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public Nullable<short> ACP_Type { get; set; }
        public Nullable<short> ACP_Champ { get; set; }
        public string ACP_ComptaCPT_CompteG { get; set; }
        public string ACP_ComptaCPT_CompteA { get; set; }
        public string ACP_ComptaCPT_Taxe1 { get; set; }
        public string ACP_ComptaCPT_Taxe2 { get; set; }
        public string ACP_ComptaCPT_Taxe3 { get; set; }
        public Nullable<System.DateTime> ACP_ComptaCPT_Date1 { get; set; }
        public Nullable<System.DateTime> ACP_ComptaCPT_Date2 { get; set; }
        public Nullable<System.DateTime> ACP_ComptaCPT_Date3 { get; set; }
        public string ACP_ComptaCPT_TaxeAnc1 { get; set; }
        public string ACP_ComptaCPT_TaxeAnc2 { get; set; }
        public string ACP_ComptaCPT_TaxeAnc3 { get; set; }
        public Nullable<short> ACP_TypeFacture { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
    }
}
