//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTCLIENT
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public Nullable<short> AC_Categorie { get; set; }
        public Nullable<decimal> AC_PrixVen { get; set; }
        public Nullable<decimal> AC_Coef { get; set; }
        public Nullable<short> AC_PrixTTC { get; set; }
        public Nullable<short> AC_Arrondi { get; set; }
        public Nullable<short> AC_QteMont { get; set; }
        public Nullable<short> EG_Champ { get; set; }
        public Nullable<decimal> AC_PrixDev { get; set; }
        public Nullable<short> AC_Devise { get; set; }
        public string CT_Num { get; set; }
        public byte[] cbCT_Num { get; set; }
        public Nullable<decimal> AC_Remise { get; set; }
        public Nullable<short> AC_Calcul { get; set; }
        public Nullable<short> AC_TypeRem { get; set; }
        public string AC_RefClient { get; set; }
        public byte[] cbAC_RefClient { get; set; }
        public Nullable<decimal> AC_CoefNouv { get; set; }
        public Nullable<decimal> AC_PrixVenNouv { get; set; }
        public Nullable<decimal> AC_PrixDevNouv { get; set; }
        public Nullable<decimal> AC_RemiseNouv { get; set; }
        public Nullable<System.DateTime> AC_DateApplication { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
    }
}
