//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTSTOCK
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public int DE_No { get; set; }
        public Nullable<decimal> AS_QteMini { get; set; }
        public Nullable<decimal> AS_QteMaxi { get; set; }
        public Nullable<decimal> AS_MontSto { get; set; }
        public Nullable<decimal> AS_QteSto { get; set; }
        public Nullable<decimal> AS_QteRes { get; set; }
        public Nullable<decimal> AS_QteCom { get; set; }
        public Nullable<short> AS_Principal { get; set; }
        public Nullable<decimal> AS_QteResCM { get; set; }
        public Nullable<decimal> AS_QteComCM { get; set; }
        public Nullable<decimal> AS_QtePrepa { get; set; }
        public Nullable<int> DP_NoPrincipal { get; set; }
        public Nullable<int> cbDP_NoPrincipal { get; set; }
        public Nullable<int> DP_NoControle { get; set; }
        public Nullable<int> cbDP_NoControle { get; set; }
        public Nullable<decimal> AS_QteAControler { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
        public Nullable<short> AS_Mouvemente { get; set; }
    }
}
