//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTICLESALLPRICE
    {
        public long RowID { get; set; }
        public string AR_Ref { get; set; }
        public string AR_Design { get; set; }
        public string FA_CodeFamille { get; set; }
        public Nullable<int> CL_No1 { get; set; }
        public Nullable<int> CL_No2 { get; set; }
        public Nullable<int> CL_No3 { get; set; }
        public Nullable<int> CL_No4 { get; set; }
        public string AR_Photo { get; set; }
        public string EC_Enumere { get; set; }
        public Nullable<decimal> EC_Quantite { get; set; }
        public string STATUT { get; set; }
        public Nullable<decimal> Prix_Gros { get; set; }
        public Nullable<decimal> Prix_details { get; set; }
        public Nullable<decimal> Prix_Adh { get; set; }
        public string PROMOTION { get; set; }
        public int COULEUR { get; set; }
    }
}
