//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_COMPTET
    {
        public string CT_Num { get; set; }
        public byte[] cbCT_Num { get; set; }
        public string CT_Intitule { get; set; }
        public Nullable<short> CT_Type { get; set; }
        public string CG_NumPrinc { get; set; }
        public string CT_Qualite { get; set; }
        public string CT_Classement { get; set; }
        public byte[] cbCT_Classement { get; set; }
        public string CT_Contact { get; set; }
        public string CT_Adresse { get; set; }
        public string CT_Complement { get; set; }
        public string CT_CodePostal { get; set; }
        public byte[] cbCT_CodePostal { get; set; }
        public string CT_Ville { get; set; }
        public string CT_CodeRegion { get; set; }
        public string CT_Pays { get; set; }
        public string CT_Raccourci { get; set; }
        public byte[] cbCT_Raccourci { get; set; }
        public Nullable<short> BT_Num { get; set; }
        public Nullable<short> N_Devise { get; set; }
        public string CT_Ape { get; set; }
        public string CT_Identifiant { get; set; }
        public string CT_Siret { get; set; }
        public string CT_Statistique01 { get; set; }
        public string CT_Statistique02 { get; set; }
        public string CT_Statistique03 { get; set; }
        public string CT_Statistique04 { get; set; }
        public string CT_Statistique05 { get; set; }
        public string CT_Statistique06 { get; set; }
        public string CT_Statistique07 { get; set; }
        public string CT_Statistique08 { get; set; }
        public string CT_Statistique09 { get; set; }
        public string CT_Statistique10 { get; set; }
        public string CT_Commentaire { get; set; }
        public Nullable<decimal> CT_Encours { get; set; }
        public Nullable<decimal> CT_Assurance { get; set; }
        public string CT_NumPayeur { get; set; }
        public byte[] cbCT_NumPayeur { get; set; }
        public Nullable<short> N_Risque { get; set; }
        public Nullable<int> CO_No { get; set; }
        public Nullable<int> cbCO_No { get; set; }
        public Nullable<short> N_CatTarif { get; set; }
        public Nullable<decimal> CT_Taux01 { get; set; }
        public Nullable<decimal> CT_Taux02 { get; set; }
        public Nullable<decimal> CT_Taux03 { get; set; }
        public Nullable<decimal> CT_Taux04 { get; set; }
        public Nullable<short> N_CatCompta { get; set; }
        public Nullable<short> N_Period { get; set; }
        public Nullable<short> CT_Facture { get; set; }
        public Nullable<short> CT_BLFact { get; set; }
        public Nullable<short> CT_Langue { get; set; }
        public Nullable<short> N_Expedition { get; set; }
        public Nullable<short> N_Condition { get; set; }
        public Nullable<short> CT_Saut { get; set; }
        public Nullable<short> CT_Lettrage { get; set; }
        public Nullable<short> CT_ValidEch { get; set; }
        public Nullable<short> CT_Sommeil { get; set; }
        public Nullable<int> DE_No { get; set; }
        public Nullable<int> cbDE_No { get; set; }
        public Nullable<short> CT_ControlEnc { get; set; }
        public Nullable<short> CT_NotRappel { get; set; }
        public Nullable<short> N_Analytique { get; set; }
        public Nullable<short> cbN_Analytique { get; set; }
        public string CA_Num { get; set; }
        public byte[] cbCA_Num { get; set; }
        public string CT_Telephone { get; set; }
        public string CT_Telecopie { get; set; }
        public string CT_EMail { get; set; }
        public string CT_Site { get; set; }
        public string CT_Coface { get; set; }
        public Nullable<short> CT_Surveillance { get; set; }
        public Nullable<System.DateTime> CT_SvDateCreate { get; set; }
        public string CT_SvFormeJuri { get; set; }
        public string CT_SvEffectif { get; set; }
        public Nullable<decimal> CT_SvCA { get; set; }
        public Nullable<decimal> CT_SvResultat { get; set; }
        public Nullable<short> CT_SvIncident { get; set; }
        public Nullable<System.DateTime> CT_SvDateIncid { get; set; }
        public Nullable<short> CT_SvPrivil { get; set; }
        public string CT_SvRegul { get; set; }
        public string CT_SvCotation { get; set; }
        public Nullable<System.DateTime> CT_SvDateMaj { get; set; }
        public string CT_SvObjetMaj { get; set; }
        public Nullable<System.DateTime> CT_SvDateBilan { get; set; }
        public Nullable<short> CT_SvNbMoisBilan { get; set; }
        public Nullable<short> N_AnalytiqueIFRS { get; set; }
        public Nullable<short> cbN_AnalytiqueIFRS { get; set; }
        public string CA_NumIFRS { get; set; }
        public Nullable<short> CT_PrioriteLivr { get; set; }
        public Nullable<short> CT_LivrPartielle { get; set; }
        public Nullable<int> MR_No { get; set; }
        public Nullable<int> cbMR_No { get; set; }
        public Nullable<short> CT_NotPenal { get; set; }
        public Nullable<int> EB_No { get; set; }
        public Nullable<int> cbEB_No { get; set; }
        public string CT_NumCentrale { get; set; }
        public byte[] cbCT_NumCentrale { get; set; }
        public Nullable<System.DateTime> CT_DateFermeDebut { get; set; }
        public Nullable<System.DateTime> CT_DateFermeFin { get; set; }
        public Nullable<short> CT_FactureElec { get; set; }
        public Nullable<short> CT_TypeNIF { get; set; }
        public string CT_RepresentInt { get; set; }
        public string CT_RepresentNIF { get; set; }
        public Nullable<short> CT_EdiCodeType { get; set; }
        public string CT_EdiCode { get; set; }
        public string CT_EdiCodeSage { get; set; }
        public Nullable<short> CT_ProfilSoc { get; set; }
        public Nullable<short> CT_StatutContrat { get; set; }
        public Nullable<System.DateTime> CT_DateMAJ { get; set; }
        public Nullable<short> CT_EchangeRappro { get; set; }
        public Nullable<short> CT_EchangeCR { get; set; }
        public Nullable<int> PI_NoEchange { get; set; }
        public Nullable<int> cbPI_NoEchange { get; set; }
        public Nullable<short> CT_BonAPayer { get; set; }
        public Nullable<short> CT_DelaiTransport { get; set; }
        public Nullable<short> CT_DelaiAppro { get; set; }
        public string CT_LangueISO2 { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public string ACODE { get; set; }
        public string CREDIT { get; set; }
        public Nullable<decimal> Montant_Credit { get; set; }
        public Nullable<decimal> OBJECTIF_MENSUEL { get; set; }
        public Nullable<System.DateTime> DATE_FIN_CREDIT { get; set; }
        public string ECHEANCE { get; set; }
        public string GP { get; set; }
        public Nullable<decimal> SOLDE { get; set; }
        public string TYPE_CLT { get; set; }
        public Nullable<decimal> Taux_Ret { get; set; }
        public string anx { get; set; }
        public string TypMont { get; set; }
        public Nullable<System.DateTime> Date_Debut_Credit { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
        public Nullable<short> CT_AnnulationCR { get; set; }
        public Nullable<short> CT_CessionCreance { get; set; }
        public string CT_Facebook { get; set; }
        public string CT_LinkedIn { get; set; }
        public Nullable<short> CT_ExclureTrait { get; set; }
        public Nullable<short> CT_GDPR { get; set; }
        public Nullable<short> CT_Prospect { get; set; }
        public byte[] cbCG_NumPrinc { get; set; }
        public Nullable<System.DateTime> CT_DATECREATE { get; set; }
    }
}
