//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_COLLABORATEUR
    {
        public Nullable<int> CO_No { get; set; }
        public string CO_Nom { get; set; }
        public byte[] cbCO_Nom { get; set; }
        public string CO_Prenom { get; set; }
        public byte[] cbCO_Prenom { get; set; }
        public string CO_Fonction { get; set; }
        public byte[] cbCO_Fonction { get; set; }
        public string CO_Adresse { get; set; }
        public string CO_Complement { get; set; }
        public string CO_CodePostal { get; set; }
        public string CO_Ville { get; set; }
        public string CO_CodeRegion { get; set; }
        public string CO_Pays { get; set; }
        public string CO_Service { get; set; }
        public Nullable<short> CO_Vendeur { get; set; }
        public Nullable<short> CO_Caissier { get; set; }
        public Nullable<short> CO_Acheteur { get; set; }
        public string CO_Telephone { get; set; }
        public string CO_Telecopie { get; set; }
        public string CO_EMail { get; set; }
        public Nullable<short> CO_Receptionnaire { get; set; }
        public Nullable<int> PROT_No { get; set; }
        public Nullable<int> cbPROT_No { get; set; }
        public string CO_TelPortable { get; set; }
        public Nullable<short> CO_ChargeRecouvr { get; set; }
        public string CO_Matricule { get; set; }
        public byte[] cbCO_Matricule { get; set; }
        public Nullable<short> CO_Financier { get; set; }
        public Nullable<short> CO_Transmission { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
        public string CO_Facebook { get; set; }
        public string CO_LinkedIn { get; set; }
        public string CO_Skype { get; set; }
    }
}
