//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_COMPTETV
    {
        public string CT_Num { get; set; }
        public string CT_Intitule { get; set; }
        public string CT_Adresse { get; set; }
        public string CT_Ville { get; set; }
        public string CT_Identifiant { get; set; }
        public string CT_Telephone { get; set; }
        public Nullable<int> CO_No { get; set; }
        public Nullable<short> N_CatTarif { get; set; }
    }
}
