//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_CREGLEMENT
    {
        public Nullable<int> RG_No { get; set; }
        public string CT_NumPayeur { get; set; }
        public byte[] cbCT_NumPayeur { get; set; }
        public Nullable<System.DateTime> RG_Date { get; set; }
        public string RG_Reference { get; set; }
        public string RG_Libelle { get; set; }
        public Nullable<decimal> RG_Montant { get; set; }
        public Nullable<decimal> RG_MontantDev { get; set; }
        public Nullable<short> N_Reglement { get; set; }
        public Nullable<short> RG_Impute { get; set; }
        public Nullable<short> RG_Compta { get; set; }
        public Nullable<int> EC_No { get; set; }
        public Nullable<int> cbEC_No { get; set; }
        public Nullable<short> RG_Type { get; set; }
        public Nullable<decimal> RG_Cours { get; set; }
        public Nullable<short> N_Devise { get; set; }
        public string JO_Num { get; set; }
        public string CG_NumCont { get; set; }
        public byte[] cbCG_NumCont { get; set; }
        public Nullable<System.DateTime> RG_Impaye { get; set; }
        public string CG_Num { get; set; }
        public byte[] cbCG_Num { get; set; }
        public Nullable<short> RG_TypeReg { get; set; }
        public string RG_Heure { get; set; }
        public string RG_Piece { get; set; }
        public byte[] cbRG_Piece { get; set; }
        public Nullable<int> CA_No { get; set; }
        public Nullable<int> cbCA_No { get; set; }
        public Nullable<int> CO_NoCaissier { get; set; }
        public Nullable<int> cbCO_NoCaissier { get; set; }
        public Nullable<short> RG_Banque { get; set; }
        public Nullable<short> RG_Transfere { get; set; }
        public short RG_Cloture { get; set; }
        public Nullable<short> RG_Ticket { get; set; }
        public Nullable<short> RG_Souche { get; set; }
        public string CT_NumPayeurOrig { get; set; }
        public byte[] cbCT_NumPayeurOrig { get; set; }
        public Nullable<System.DateTime> RG_DateEchCont { get; set; }
        public string CG_NumEcart { get; set; }
        public byte[] cbCG_NumEcart { get; set; }
        public string JO_NumEcart { get; set; }
        public Nullable<decimal> RG_MontantEcart { get; set; }
        public Nullable<int> RG_NoBonAchat { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
        public Nullable<short> RG_Valide { get; set; }
        public Nullable<decimal> RG_Anterieur { get; set; }
        public Nullable<decimal> RG_MontantCommission { get; set; }
        public Nullable<decimal> RG_MontantNet { get; set; }
        public byte[] cbHash { get; set; }
        public Nullable<short> cbHashVersion { get; set; }
        public Nullable<System.DateTime> cbHashDate { get; set; }
        public Nullable<int> cbHashOrder { get; set; }
    }
}
