//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_DOCREGL
    {
        public Nullable<int> DR_No { get; set; }
        public Nullable<short> DO_Domaine { get; set; }
        public Nullable<short> DO_Type { get; set; }
        public string DO_Piece { get; set; }
        public byte[] cbDO_Piece { get; set; }
        public Nullable<short> DR_TypeRegl { get; set; }
        public Nullable<System.DateTime> DR_Date { get; set; }
        public string DR_Libelle { get; set; }
        public Nullable<decimal> DR_Pourcent { get; set; }
        public Nullable<decimal> DR_Montant { get; set; }
        public Nullable<decimal> DR_MontantDev { get; set; }
        public Nullable<short> DR_Equil { get; set; }
        public Nullable<int> EC_No { get; set; }
        public Nullable<int> cbEC_No { get; set; }
        public Nullable<short> DR_Regle { get; set; }
        public Nullable<short> N_Reglement { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<decimal> IMP { get; set; }
        public Nullable<decimal> BQ { get; set; }
        public Nullable<decimal> lien_reg { get; set; }
        public Nullable<decimal> mt_echeance { get; set; }
        public Nullable<int> supp { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
        public Nullable<int> CA_No { get; set; }
        public Nullable<int> cbCA_No { get; set; }
        public Nullable<short> DO_DocType { get; set; }
        public byte[] cbHash { get; set; }
        public Nullable<short> cbHashVersion { get; set; }
        public Nullable<System.DateTime> cbHashDate { get; set; }
        public Nullable<int> cbHashOrder { get; set; }
    }
}
