//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_LIVRAISON
    {
        public int LI_No { get; set; }
        public string CT_Num { get; set; }
        public byte[] cbCT_Num { get; set; }
        public string LI_Intitule { get; set; }
        public byte[] cbLI_Intitule { get; set; }
        public string LI_Adresse { get; set; }
        public string LI_Complement { get; set; }
        public string LI_CodePostal { get; set; }
        public string LI_Ville { get; set; }
        public string LI_CodeRegion { get; set; }
        public string LI_Pays { get; set; }
        public string LI_Contact { get; set; }
        public Nullable<short> N_Expedition { get; set; }
        public Nullable<short> N_Condition { get; set; }
        public Nullable<short> LI_Principal { get; set; }
        public string LI_Telephone { get; set; }
        public string LI_Telecopie { get; set; }
        public string LI_EMail { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<int> sup { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
    }
}
