//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_POSITIONCOM
    {
        public int id { get; set; }
        public Nullable<int> CO_No { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string DateP { get; set; }
    }
}
