//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_TAXE
    {
        public string TA_Intitule { get; set; }
        public byte[] cbTA_Intitule { get; set; }
        public Nullable<short> TA_TTaux { get; set; }
        public Nullable<decimal> TA_Taux { get; set; }
        public Nullable<short> TA_Type { get; set; }
        public string CG_Num { get; set; }
        public byte[] cbCG_Num { get; set; }
        public int TA_No { get; set; }
        public string TA_Code { get; set; }
        public byte[] cbTA_Code { get; set; }
        public Nullable<short> TA_NP { get; set; }
        public Nullable<short> TA_Sens { get; set; }
        public Nullable<short> TA_Provenance { get; set; }
        public string TA_Regroup { get; set; }
        public byte[] cbTA_Regroup { get; set; }
        public Nullable<decimal> TA_Assujet { get; set; }
        public string TA_GrilleBase { get; set; }
        public string TA_GrilleTaxe { get; set; }
        public string TA_EdiCode { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> cbCreation { get; set; }
        public Nullable<System.Guid> cbCreationUser { get; set; }
    }
}
