//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_REGLEMENT
    {
        public string R_Intitule { get; set; }
        public string R_Code { get; set; }
        public Nullable<short> R_ModePaieDebit { get; set; }
        public Nullable<short> R_ModePaieCredit { get; set; }
        public string IB_AFBDecaissPrinc { get; set; }
        public string IB_AFBEncaissPrinc { get; set; }
        public Nullable<int> EB_NoDecaiss { get; set; }
        public Nullable<int> EB_NoEncaiss { get; set; }
        public string R_EdiCode { get; set; }
        public Nullable<short> cbIndice { get; set; }
        public int cbMarq { get; set; }
        public Nullable<short> R_PaiementLigne { get; set; }
    }
}
