//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLDE_CLT
    {
        public string CT_Num { get; set; }
        public string CT_Intitule { get; set; }
        public string DO_Piece { get; set; }
        public Nullable<System.DateTime> DO_Date { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
        public string Type { get; set; }
        public string Stype { get; set; }
        public string CO_Nom { get; set; }
        public string CO_Prenom { get; set; }
    }
}
