//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_ART
    {
        public long RowID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Mois { get; set; }
        public string AR_Ref { get; set; }
        public string AR_Design { get; set; }
        public Nullable<int> CO_No { get; set; }
        public Nullable<decimal> Qte { get; set; }
        public Nullable<decimal> CA { get; set; }
    }
}
