//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_CLT
    {
        public long RowID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Mois { get; set; }
        public string CT_Num { get; set; }
        public string CT_Intitule { get; set; }
        public Nullable<int> CO_No { get; set; }
        public Nullable<decimal> CA { get; set; }
    }
}
